### ISSUE TITLE
[FEATURE] Database init and Use API

### ISSUE THREAD

**Issue by jjj5306** [kdhqwe1030/R_yu-gi-oh#5]
## Description for development features
SQLite를 사용한 DataBase 스키마 정의 및 API를 사용하여 CardInfo Table 채우기 구현
<br>

## Todo-lists
- [x] DataBase 스키마 정의
- [x] CardInfo Table 채우기
- [x] Service Layer 생성, API 사용하는 함수 구현
