### ISSUE TITLE
[FEATURE] Add database api data and Make data unique

### ISSUE THREAD

**Issue by jjj5306** [kdhqwe1030/R_yu-gi-oh#8]
## Description for development features
DB 초기화 및 API 데이터로 채우기, 중복 제거 구현

<br>

## Todo-lists
- [x] DataBase 초기화 커맨드 작성
- [x] API 데이터로 채우기
- [x] API 데이터 중복 제거
